// Core — generated by @web-kits/audio (do not edit)
// patch: Core
import type { SoundDefinition, SoundPatch } from '@web-kits/audio'

export const click: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 200, end: 700 }, fm: { ratio: 0.5, depth: 80 } },
  envelope: { attack: 0, decay: 0.06, sustain: 0, release: 0.02 },
  gain: 0.25,
}
export const tap: SoundDefinition = {
  source: { type: 'sine', frequency: 1300, fm: { ratio: 0.5, depth: 100 } },
  envelope: { attack: 0, decay: 0.015, sustain: 0, release: 0.005 },
  gain: 0.2,
}
export const keyPress: SoundDefinition = {
  source: { type: 'sine', frequency: 1300, fm: { ratio: 0.5, depth: 80 } },
  envelope: { attack: 0, decay: 0.012, sustain: 0, release: 0.004 },
  gain: 0.18,
}
export const checkbox: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 250, end: 800 }, fm: { ratio: 0.5, depth: 60 } },
  envelope: { attack: 0, decay: 0.05, sustain: 0, release: 0.015 },
  gain: 0.22,
}
export const radio: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 300, end: 900 }, fm: { ratio: 0.5, depth: 50 } },
  envelope: { attack: 0, decay: 0.04, sustain: 0, release: 0.012 },
  gain: 0.2,
}
export const tick: SoundDefinition = {
  source: { type: 'sine', frequency: 1500, fm: { ratio: 0.5, depth: 60 } },
  envelope: { attack: 0, decay: 0.01, sustain: 0, release: 0.004 },
  gain: 0.15,
}
export const scrollSnap: SoundDefinition = {
  source: { type: 'sine', frequency: 1400, fm: { ratio: 0.5, depth: 50 } },
  envelope: { attack: 0, decay: 0.008, sustain: 0, release: 0.003 },
  gain: 0.08,
}
export const focus: SoundDefinition = {
  source: { type: 'sine', frequency: 1300, fm: { ratio: 0.5, depth: 40 } },
  envelope: { attack: 0, decay: 0.02, sustain: 0, release: 0.008 },
  gain: 0.06,
}
export const blur: SoundDefinition = {
  source: { type: 'sine', frequency: 1100, fm: { ratio: 0.5, depth: 30 } },
  envelope: { attack: 0, decay: 0.018, sustain: 0, release: 0.008 },
  gain: 0.04,
}
export const toggleOn: SoundDefinition = {
  layers: [
    {
      source: { type: 'sine', frequency: 2093 },
      envelope: { attack: 0, decay: 0.012, sustain: 0, release: 0.004 },
      gain: 0.2,
    },
    {
      source: { type: 'sine', frequency: 3136 },
      envelope: { attack: 0, decay: 0.012, sustain: 0, release: 0.004 },
      delay: 0.025,
      gain: 0.2,
    },
  ],
}
export const toggleOff: SoundDefinition = {
  layers: [
    {
      source: { type: 'sine', frequency: 3136 },
      envelope: { attack: 0, decay: 0.012, sustain: 0, release: 0.004 },
      gain: 0.2,
    },
    {
      source: { type: 'sine', frequency: 2093 },
      envelope: { attack: 0, decay: 0.012, sustain: 0, release: 0.004 },
      delay: 0.025,
      gain: 0.2,
    },
  ],
}
export const hover: SoundDefinition = {
  source: { type: 'sine', frequency: 1300 },
  envelope: { attack: 0.005, decay: 0.015, sustain: 0, release: 0.008 },
  gain: 0.04,
}
export const select: SoundDefinition = {
  source: { type: 'sine', frequency: 1400, fm: { ratio: 0.5, depth: 60 } },
  envelope: { attack: 0, decay: 0.05, sustain: 0, release: 0.015 },
  gain: 0.2,
}
export const deselect: SoundDefinition = {
  source: { type: 'sine', frequency: 1200, fm: { ratio: 0.5, depth: 60 } },
  envelope: { attack: 0, decay: 0.04, sustain: 0, release: 0.012 },
  gain: 0.16,
}
export const pop: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 400, end: 150 } },
  envelope: { attack: 0, decay: 0.08, sustain: 0, release: 0.025 },
  gain: 0.25,
}
export const boop: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 600, end: 250 }, fm: { ratio: 0.5, depth: 40 } },
  envelope: { attack: 0, decay: 0.1, sustain: 0, release: 0.03 },
  gain: 0.2,
}
export const bounce: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 350, end: 180 } },
  envelope: { attack: 0, decay: 0.12, sustain: 0, release: 0.04 },
  gain: 0.22,
}
export const spring: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 400, end: 900 }, fm: { ratio: 0.5, depth: 50 } },
  envelope: { attack: 0, decay: 0.15, sustain: 0.03, release: 0.05 },
  gain: 0.18,
}
export const expand: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 500, end: 700 } },
  envelope: { attack: 0.003, decay: 0.1, sustain: 0.02, release: 0.04 },
  gain: 0.12,
}
export const collapse: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 700, end: 500 } },
  envelope: { attack: 0.003, decay: 0.1, sustain: 0.02, release: 0.04 },
  gain: 0.12,
}
export const success: SoundDefinition = {
  layers: [
    {
      source: { type: 'sine', frequency: 523 },
      envelope: { attack: 0.003, decay: 0.3, sustain: 0.06, release: 0.1 },
      gain: 0.16,
    },
    {
      source: { type: 'sine', frequency: 659 },
      envelope: { attack: 0.003, decay: 0.28, sustain: 0.05, release: 0.1 },
      delay: 0.07,
      gain: 0.14,
    },
    {
      source: { type: 'sine', frequency: { start: 784, end: 880 } },
      envelope: { attack: 0.003, decay: 0.32, sustain: 0.06, release: 0.12 },
      delay: 0.14,
      gain: 0.15,
    },
  ],
}
export const complete: SoundDefinition = {
  layers: [
    {
      source: { type: 'sine', frequency: 523 },
      envelope: { attack: 0.003, decay: 0.35, sustain: 0.05, release: 0.1 },
      gain: 0.15,
    },
    {
      source: { type: 'sine', frequency: 659 },
      envelope: { attack: 0.003, decay: 0.35, sustain: 0.05, release: 0.1 },
      delay: 0.015,
      gain: 0.13,
    },
    {
      source: { type: 'sine', frequency: 784 },
      envelope: { attack: 0.003, decay: 0.35, sustain: 0.05, release: 0.1 },
      delay: 0.03,
      gain: 0.12,
    },
    {
      source: { type: 'sine', frequency: { start: 1046, end: 1175 } },
      envelope: { attack: 0.003, decay: 0.3, sustain: 0.04, release: 0.12 },
      delay: 0.045,
      gain: 0.1,
    },
  ],
}
export const levelUp: SoundDefinition = {
  layers: [
    {
      source: { type: 'sine', frequency: 440 },
      envelope: { attack: 0.003, decay: 0.25, sustain: 0.06, release: 0.1 },
      gain: 0.15,
    },
    {
      source: { type: 'sine', frequency: 554 },
      envelope: { attack: 0.003, decay: 0.25, sustain: 0.05, release: 0.1 },
      delay: 0.07,
      gain: 0.14,
    },
    {
      source: { type: 'sine', frequency: 660 },
      envelope: { attack: 0.003, decay: 0.28, sustain: 0.05, release: 0.1 },
      delay: 0.14,
      gain: 0.13,
    },
    {
      source: { type: 'sine', frequency: { start: 880, end: 990 } },
      envelope: { attack: 0.003, decay: 0.22, sustain: 0.04, release: 0.12 },
      delay: 0.21,
      gain: 0.08,
    },
  ],
}
export const confetti: SoundDefinition = {
  layers: [
    {
      source: { type: 'sine', frequency: 523 },
      envelope: { attack: 0.002, decay: 0.18, sustain: 0.04, release: 0.08 },
      gain: 0.14,
    },
    {
      source: { type: 'sine', frequency: 659 },
      envelope: { attack: 0.002, decay: 0.18, sustain: 0.04, release: 0.08 },
      delay: 0.06,
      gain: 0.14,
    },
    {
      source: { type: 'sine', frequency: 784 },
      envelope: { attack: 0.002, decay: 0.18, sustain: 0.03, release: 0.08 },
      delay: 0.12,
      gain: 0.12,
    },
    {
      source: { type: 'sine', frequency: { start: 1047, end: 1175 } },
      envelope: { attack: 0.002, decay: 0.2, sustain: 0.03, release: 0.1 },
      delay: 0.18,
      gain: 0.1,
    },
  ],
}
export const save: SoundDefinition = {
  layers: [
    {
      source: { type: 'sine', frequency: { start: 880, end: 1046 } },
      envelope: { attack: 0, decay: 0.1, sustain: 0.03, release: 0.04 },
      gain: 0.14,
    },
    {
      source: { type: 'sine', frequency: { start: 1046, end: 1175 } },
      envelope: { attack: 0, decay: 0.1, sustain: 0.02, release: 0.04 },
      delay: 0.08,
      gain: 0.1,
    },
  ],
}
export const ding: SoundDefinition = {
  source: { type: 'sine', frequency: 880, fm: { ratio: 3.5, depth: 300 } },
  envelope: { attack: 0, decay: 0.6, sustain: 0.04, release: 0.25 },
  effects: [{ type: 'reverb', decay: 0.8, damping: 0.6, mix: 0.15 }],
  gain: 0.18,
}
export const notification: SoundDefinition = {
  layers: [
    {
      source: { type: 'sine', frequency: 780, fm: { ratio: 1.5, depth: 150 } },
      envelope: { attack: 0, decay: 0.4, sustain: 0.04, release: 0.15 },
      effects: [{ type: 'reverb', decay: 0.6, damping: 0.6, mix: 0.12 }],
      gain: 0.16,
    },
    {
      source: { type: 'sine', frequency: 1170, fm: { ratio: 1.5, depth: 120 } },
      envelope: { attack: 0, decay: 0.35, sustain: 0.03, release: 0.15 },
      delay: 0.1,
      effects: [{ type: 'reverb', decay: 0.6, damping: 0.6, mix: 0.12 }],
      gain: 0.14,
    },
  ],
}
export const mention: SoundDefinition = {
  source: { type: 'sine', frequency: 660, fm: { ratio: 2.5, depth: 150 } },
  envelope: { attack: 0.003, decay: 0.5, sustain: 0.05, release: 0.2 },
  effects: [{ type: 'reverb', decay: 0.6, damping: 0.5, mix: 0.1 }],
  gain: 0.14,
}
export const badge: SoundDefinition = {
  source: { type: 'sine', frequency: 1100, fm: { ratio: 2.76, depth: 350 } },
  envelope: { attack: 0, decay: 0.35, sustain: 0.04, release: 0.15 },
  effects: [{ type: 'reverb', decay: 0.5, damping: 0.6, mix: 0.1 }],
  gain: 0.16,
}
export const info: SoundDefinition = {
  source: { type: 'sine', frequency: 880, fm: { ratio: 2, depth: 120 } },
  envelope: { attack: 0.003, decay: 0.3, sustain: 0.04, release: 0.12 },
  gain: 0.14,
}
export const sparkle: SoundDefinition = {
  layers: [
    {
      source: { type: 'sine', frequency: 1047, detune: 7, fm: { ratio: 3.5, depth: 200 } },
      envelope: { attack: 0, decay: 0.4, sustain: 0.04, release: 0.18 },
      effects: [{ type: 'reverb', decay: 0.8, damping: 0.5, mix: 0.15 }],
      gain: 0.12,
    },
    {
      source: { type: 'sine', frequency: 1050, fm: { ratio: 3.5, depth: 180 } },
      envelope: { attack: 0, decay: 0.38, sustain: 0.03, release: 0.18 },
      gain: 0.08,
    },
  ],
}
export const star: SoundDefinition = {
  source: { type: 'sine', frequency: 880, fm: { ratio: 2.76, depth: 250 } },
  envelope: { attack: 0, decay: 0.4, sustain: 0.04, release: 0.18 },
  effects: [{ type: 'reverb', decay: 0.6, damping: 0.5, mix: 0.12 }],
  gain: 0.14,
}
export const error: SoundDefinition = {
  layers: [
    {
      source: { type: 'sawtooth', frequency: { start: 320, end: 140 } },
      filter: { type: 'lowpass', frequency: 1200 },
      envelope: { attack: 0, decay: 0.25, sustain: 0, release: 0.08 },
      gain: 0.22,
    },
    {
      source: { type: 'square', frequency: { start: 180, end: 80 } },
      filter: { type: 'lowpass', frequency: 800 },
      envelope: { attack: 0, decay: 0.2, sustain: 0, release: 0.06 },
      delay: 0.03,
      gain: 0.12,
    },
  ],
}
export const _delete: SoundDefinition = {
  layers: [
    {
      source: { type: 'sawtooth', frequency: { start: 300, end: 100 } },
      filter: { type: 'lowpass', frequency: 800 },
      envelope: { attack: 0, decay: 0.3, sustain: 0, release: 0.08 },
      gain: 0.18,
    },
    {
      source: { type: 'square', frequency: { start: 200, end: 60 } },
      filter: { type: 'lowpass', frequency: 600 },
      envelope: { attack: 0, decay: 0.25, sustain: 0, release: 0.06 },
      delay: 0.02,
      gain: 0.1,
    },
  ],
}
export const warning: SoundDefinition = {
  layers: [
    {
      source: { type: 'triangle', frequency: 440 },
      envelope: { attack: 0, decay: 0.18, sustain: 0.06, release: 0.06 },
      gain: 0.2,
    },
    {
      source: { type: 'triangle', frequency: 466 },
      envelope: { attack: 0, decay: 0.18, sustain: 0.06, release: 0.06 },
      delay: 0.01,
      gain: 0.15,
    },
  ],
}
export const swoosh: SoundDefinition = {
  source: { type: 'noise', color: 'white' },
  filter: { type: 'bandpass', frequency: 300, resonance: 1.8, envelope: { attack: 0.01, peak: 4000, decay: 0.08 } },
  envelope: { attack: 0.01, decay: 0.12, sustain: 0, release: 0.04 },
  gain: 0.12,
}
export const whoosh: SoundDefinition = {
  source: { type: 'noise', color: 'white' },
  filter: { type: 'bandpass', frequency: 300, resonance: 1.5, envelope: { attack: 0.04, peak: 4000, decay: 0.16 } },
  envelope: { attack: 0.02, decay: 0.25, sustain: 0, release: 0.08 },
  gain: 0.15,
}
export const pageEnter: SoundDefinition = {
  source: { type: 'noise', color: 'white' },
  filter: { type: 'bandpass', frequency: 400, resonance: 1.2, envelope: { attack: 0.03, peak: 3000, decay: 0.15 } },
  envelope: { attack: 0.02, decay: 0.2, sustain: 0, release: 0.06 },
  gain: 0.08,
}
export const pageExit: SoundDefinition = {
  source: { type: 'noise', color: 'pink' },
  filter: { type: 'bandpass', frequency: 2500, resonance: 1.2, envelope: { decay: 0.18, peak: 400 } },
  envelope: { attack: 0.01, decay: 0.2, sustain: 0, release: 0.06 },
  gain: 0.07,
}
export const tabSwitch: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 1100, end: 1500 }, fm: { ratio: 0.5, depth: 50 } },
  envelope: { attack: 0, decay: 0.05, sustain: 0, release: 0.015 },
  gain: 0.18,
}
export const drawerOpen: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 350, end: 1000 } },
  envelope: { attack: 0, decay: 0.1, sustain: 0, release: 0.03 },
  gain: 0.08,
}
export const drawerClose: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 800, end: 350 } },
  envelope: { attack: 0, decay: 0.1, sustain: 0, release: 0.03 },
  gain: 0.06,
}
export const modalOpen: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 430, end: 1400 } },
  envelope: { attack: 0, decay: 0.08, sustain: 0, release: 0.025 },
  gain: 0.1,
}
export const modalClose: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 730, end: 430 } },
  envelope: { attack: 0, decay: 0.08, sustain: 0, release: 0.025 },
  gain: 0.08,
}
export const dropdownOpen: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 500, end: 1200 } },
  envelope: { attack: 0, decay: 0.06, sustain: 0, release: 0.02 },
  gain: 0.07,
}
export const dropdownClose: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 900, end: 500 } },
  envelope: { attack: 0, decay: 0.06, sustain: 0, release: 0.02 },
  gain: 0.05,
}
export const slide: SoundDefinition = {
  source: { type: 'noise', color: 'white' },
  filter: { type: 'bandpass', frequency: 500, resonance: 1, envelope: { attack: 0.02, peak: 3000, decay: 0.12 } },
  envelope: { attack: 0.01, decay: 0.15, sustain: 0, release: 0.05 },
  gain: 0.07,
}
export const slideUp: SoundDefinition = {
  source: { type: 'noise', color: 'white' },
  filter: { type: 'bandpass', frequency: 500, resonance: 1, envelope: { attack: 0.02, peak: 3500, decay: 0.12 } },
  envelope: { attack: 0.01, decay: 0.15, sustain: 0, release: 0.05 },
  gain: 0.07,
}
export const slideDown: SoundDefinition = {
  source: { type: 'noise', color: 'pink' },
  filter: { type: 'bandpass', frequency: 2500, resonance: 1, envelope: { decay: 0.12, peak: 500 } },
  envelope: { attack: 0.01, decay: 0.15, sustain: 0, release: 0.05 },
  gain: 0.06,
}
export const copy: SoundDefinition = {
  layers: [
    {
      source: { type: 'sine', frequency: 1200 },
      envelope: { attack: 0, decay: 0.015, sustain: 0, release: 0.006 },
      gain: 0.16,
    },
    {
      source: { type: 'sine', frequency: 1400 },
      envelope: { attack: 0, decay: 0.015, sustain: 0, release: 0.006 },
      delay: 0.04,
      gain: 0.14,
    },
  ],
}
export const send: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 500, end: 1200 } },
  envelope: { attack: 0, decay: 0.15, sustain: 0, release: 0.04 },
  gain: 0.16,
}
export const receive: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 1200, end: 700 } },
  envelope: { attack: 0, decay: 0.12, sustain: 0.02, release: 0.04 },
  gain: 0.12,
}
export const command: SoundDefinition = {
  layers: [
    {
      source: { type: 'sine', frequency: { start: 600, end: 900 } },
      envelope: { attack: 0, decay: 0.05, sustain: 0, release: 0.015 },
      gain: 0.18,
    },
    {
      source: { type: 'sine', frequency: { start: 900, end: 1100 } },
      envelope: { attack: 0, decay: 0.04, sustain: 0, release: 0.012 },
      delay: 0.04,
      gain: 0.12,
    },
  ],
}
export const escape: SoundDefinition = {
  layers: [
    {
      source: { type: 'sine', frequency: { start: 900, end: 600 } },
      envelope: { attack: 0, decay: 0.05, sustain: 0, release: 0.015 },
      gain: 0.16,
    },
    {
      source: { type: 'sine', frequency: { start: 700, end: 500 } },
      envelope: { attack: 0, decay: 0.04, sustain: 0, release: 0.012 },
      delay: 0.03,
      gain: 0.1,
    },
  ],
}
export const undo: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 900, end: 600 } },
  envelope: { attack: 0, decay: 0.12, sustain: 0.02, release: 0.04 },
  gain: 0.14,
}
export const archive: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 800, end: 550 } },
  envelope: { attack: 0.003, decay: 0.15, sustain: 0.02, release: 0.05 },
  gain: 0.12,
}
export const sync: SoundDefinition = {
  layers: [
    {
      source: { type: 'sine', frequency: 523 },
      envelope: { attack: 0, decay: 0.015, sustain: 0, release: 0.005 },
      gain: 0.14,
    },
    {
      source: { type: 'sine', frequency: 784 },
      envelope: { attack: 0, decay: 0.015, sustain: 0, release: 0.005 },
      delay: 0.04,
      gain: 0.12,
    },
  ],
}
export const heart: SoundDefinition = {
  layers: [
    {
      source: { type: 'sine', frequency: { start: 500, end: 300 } },
      envelope: { attack: 0, decay: 0.1, sustain: 0, release: 0.04 },
      gain: 0.16,
    },
    {
      source: { type: 'sine', frequency: 523, fm: { ratio: 2.5, depth: 100 } },
      envelope: { attack: 0.008, decay: 0.25, sustain: 0.04, release: 0.1 },
      gain: 0.1,
    },
  ],
}
export const streak: SoundDefinition = {
  layers: [
    {
      source: { type: 'sine', frequency: { start: 523, end: 784 } },
      envelope: { attack: 0, decay: 0.12, sustain: 0.02, release: 0.05 },
      gain: 0.16,
    },
    {
      source: { type: 'sine', frequency: { start: 526, end: 787 }, fm: { ratio: 2.5, depth: 100 } },
      envelope: { attack: 0, decay: 0.11, sustain: 0.01, release: 0.05 },
      gain: 0.08,
    },
  ],
}
export const loadingStart: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 500, end: 700 } },
  envelope: { attack: 0.008, decay: 0.12, sustain: 0.02, release: 0.05 },
  gain: 0.08,
}
export const loadingEnd: SoundDefinition = {
  layers: [
    {
      source: { type: 'sine', frequency: { start: 700, end: 880 } },
      envelope: { attack: 0, decay: 0.1, sustain: 0.02, release: 0.04 },
      gain: 0.1,
    },
    {
      source: { type: 'sine', frequency: { start: 880, end: 1046 } },
      envelope: { attack: 0, decay: 0.08, sustain: 0.01, release: 0.04 },
      delay: 0.06,
      gain: 0.08,
    },
  ],
}
export const progressTick: SoundDefinition = {
  source: { type: 'sine', frequency: 1400, fm: { ratio: 0.5, depth: 50 } },
  envelope: { attack: 0, decay: 0.01, sustain: 0, release: 0.004 },
  gain: 0.1,
}

export const _patch: SoundPatch = {
  name: 'Core',
  author: 'Raphael Salaja',
  version: '3.1.0',
  description:
    'A foundational UI sound pack with essential clicks, toggles, pops, notifications, and transitions, designed to feel clear and familiar across everyday product interactions without overwhelming the interface.',
  sounds: {
    click,
    tap,
    'key-press': keyPress,
    checkbox,
    radio,
    tick,
    'scroll-snap': scrollSnap,
    focus,
    blur,
    'toggle-on': toggleOn,
    'toggle-off': toggleOff,
    hover,
    select,
    deselect,
    pop,
    boop,
    bounce,
    spring,
    expand,
    collapse,
    success,
    complete,
    'level-up': levelUp,
    confetti,
    save,
    ding,
    notification,
    mention,
    badge,
    info,
    sparkle,
    star,
    error,
    delete: _delete,
    warning,
    swoosh,
    whoosh,
    'page-enter': pageEnter,
    'page-exit': pageExit,
    'tab-switch': tabSwitch,
    'drawer-open': drawerOpen,
    'drawer-close': drawerClose,
    'modal-open': modalOpen,
    'modal-close': modalClose,
    'dropdown-open': dropdownOpen,
    'dropdown-close': dropdownClose,
    slide,
    'slide-up': slideUp,
    'slide-down': slideDown,
    copy,
    send,
    receive,
    command,
    escape,
    undo,
    archive,
    sync,
    heart,
    streak,
    'loading-start': loadingStart,
    'loading-end': loadingEnd,
    'progress-tick': progressTick,
  },
}
