// Playful — generated by @web-kits/audio (do not edit)
// patch: Playful
import type { SoundDefinition, SoundPatch } from '@web-kits/audio'

export const tap: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 1400, end: 800 } },
  envelope: { attack: 0, decay: 0.06, sustain: 0, release: 0.02 },
  gain: 0.22,
}
export const click: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 300, end: 900 }, fm: { ratio: 0.5, depth: 60 } },
  envelope: { attack: 0, decay: 0.08, sustain: 0, release: 0.025 },
  gain: 0.25,
}
export const keyPress: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 1600, end: 1000 } },
  envelope: { attack: 0, decay: 0.04, sustain: 0, release: 0.012 },
  gain: 0.18,
}
export const toggleOn: SoundDefinition = {
  layers: [
    {
      source: { type: 'sine', frequency: { start: 400, end: 800 } },
      envelope: { attack: 0, decay: 0.08, sustain: 0, release: 0.025 },
      gain: 0.22,
    },
    {
      source: { type: 'sine', frequency: { start: 600, end: 1200 } },
      envelope: { attack: 0, decay: 0.07, sustain: 0, release: 0.02 },
      delay: 0.04,
      gain: 0.18,
    },
  ],
}
export const toggleOff: SoundDefinition = {
  layers: [
    {
      source: { type: 'sine', frequency: { start: 800, end: 400 } },
      envelope: { attack: 0, decay: 0.08, sustain: 0, release: 0.025 },
      gain: 0.22,
    },
    {
      source: { type: 'sine', frequency: { start: 600, end: 300 } },
      envelope: { attack: 0, decay: 0.07, sustain: 0, release: 0.02 },
      delay: 0.04,
      gain: 0.18,
    },
  ],
}
export const checkbox: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 350, end: 1100 }, fm: { ratio: 0.5, depth: 50 } },
  envelope: { attack: 0, decay: 0.08, sustain: 0, release: 0.025 },
  gain: 0.24,
}
export const select: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 500, end: 1000 } },
  envelope: { attack: 0, decay: 0.07, sustain: 0, release: 0.02 },
  gain: 0.2,
}
export const deselect: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 800, end: 400 } },
  envelope: { attack: 0, decay: 0.06, sustain: 0, release: 0.018 },
  gain: 0.16,
}
export const hover: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 1200, end: 1500 } },
  envelope: { attack: 0, decay: 0.03, sustain: 0, release: 0.01 },
  gain: 0.08,
}
export const tabSwitch: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 600, end: 1400 } },
  envelope: { attack: 0, decay: 0.06, sustain: 0, release: 0.018 },
  gain: 0.2,
}
export const expand: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 300, end: 900 } },
  envelope: { attack: 0, decay: 0.12, sustain: 0.02, release: 0.04 },
  gain: 0.16,
}
export const collapse: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 900, end: 300 } },
  envelope: { attack: 0, decay: 0.12, sustain: 0.02, release: 0.04 },
  gain: 0.16,
}
export const pageEnter: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 300, end: 1000 } },
  envelope: { attack: 0.005, decay: 0.15, sustain: 0, release: 0.05 },
  gain: 0.12,
}
export const pageExit: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 1000, end: 300 } },
  envelope: { attack: 0, decay: 0.15, sustain: 0, release: 0.05 },
  gain: 0.1,
}
export const success: SoundDefinition = {
  layers: [
    {
      source: { type: 'sine', frequency: { start: 400, end: 523 } },
      envelope: { attack: 0, decay: 0.15, sustain: 0.04, release: 0.06 },
      gain: 0.2,
    },
    {
      source: { type: 'sine', frequency: { start: 500, end: 659 } },
      envelope: { attack: 0, decay: 0.14, sustain: 0.03, release: 0.06 },
      delay: 0.08,
      gain: 0.18,
    },
    {
      source: { type: 'sine', frequency: { start: 600, end: 880 } },
      envelope: { attack: 0, decay: 0.16, sustain: 0.03, release: 0.06 },
      delay: 0.16,
      gain: 0.16,
    },
    {
      source: { type: 'sine', frequency: { start: 700, end: 1047 } },
      envelope: { attack: 0, decay: 0.18, sustain: 0.02, release: 0.08 },
      delay: 0.24,
      gain: 0.12,
    },
  ],
}
export const error: SoundDefinition = {
  layers: [
    {
      source: { type: 'sine', frequency: { start: 500, end: 150 }, fm: { ratio: 0.5, depth: 80 } },
      envelope: { attack: 0, decay: 0.15, sustain: 0, release: 0.05 },
      gain: 0.25,
    },
    {
      source: { type: 'sine', frequency: { start: 400, end: 100 } },
      envelope: { attack: 0, decay: 0.12, sustain: 0, release: 0.04 },
      delay: 0.05,
      gain: 0.18,
    },
  ],
}
export const warning: SoundDefinition = {
  layers: [
    {
      source: { type: 'sine', frequency: { start: 500, end: 380 } },
      envelope: { attack: 0, decay: 0.1, sustain: 0.03, release: 0.04 },
      gain: 0.22,
    },
    {
      source: { type: 'sine', frequency: { start: 520, end: 400 } },
      envelope: { attack: 0, decay: 0.1, sustain: 0.03, release: 0.04 },
      delay: 0.015,
      gain: 0.16,
    },
  ],
}
export const notification: SoundDefinition = {
  layers: [
    {
      source: { type: 'sine', frequency: { start: 500, end: 880 } },
      envelope: { attack: 0, decay: 0.18, sustain: 0.03, release: 0.06 },
      gain: 0.2,
    },
    {
      source: { type: 'sine', frequency: { start: 700, end: 1320 } },
      envelope: { attack: 0, decay: 0.15, sustain: 0.02, release: 0.05 },
      delay: 0.1,
      gain: 0.16,
    },
  ],
}
export const info: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 600, end: 900 } },
  envelope: { attack: 0, decay: 0.12, sustain: 0.02, release: 0.04 },
  gain: 0.16,
}
export const copy: SoundDefinition = {
  layers: [
    {
      source: { type: 'sine', frequency: { start: 800, end: 1200 } },
      envelope: { attack: 0, decay: 0.03, sustain: 0, release: 0.01 },
      gain: 0.18,
    },
    {
      source: { type: 'sine', frequency: { start: 1000, end: 1500 } },
      envelope: { attack: 0, decay: 0.03, sustain: 0, release: 0.01 },
      delay: 0.05,
      gain: 0.15,
    },
  ],
}
export const send: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 400, end: 1400 } },
  envelope: { attack: 0, decay: 0.15, sustain: 0, release: 0.05 },
  gain: 0.2,
}
export const _delete: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 700, end: 100 } },
  envelope: { attack: 0, decay: 0.18, sustain: 0, release: 0.06 },
  gain: 0.22,
}
export const undo: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 1000, end: 500 } },
  envelope: { attack: 0, decay: 0.1, sustain: 0, release: 0.035 },
  gain: 0.16,
}
export const pop: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 600, end: 150 }, fm: { ratio: 0.5, depth: 40 } },
  envelope: { attack: 0, decay: 0.1, sustain: 0, release: 0.035 },
  gain: 0.28,
}
export const swoosh: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 300, end: 2000 } },
  envelope: { attack: 0.008, decay: 0.12, sustain: 0, release: 0.04 },
  gain: 0.12,
}
export const slide: SoundDefinition = {
  source: { type: 'sine', frequency: { start: 500, end: 1200 } },
  envelope: { attack: 0.005, decay: 0.1, sustain: 0, release: 0.035 },
  gain: 0.1,
}

export const _patch: SoundPatch = {
  name: 'Playful',
  author: 'Raphael Salaja',
  version: '1.0.0',
  description:
    'A lively pack of bouncy pitch sweeps and energetic tones with a playful, cartoon-like character, perfect for gamified flows, rewards, and moments that should feel fun and upbeat.',
  sounds: {
    tap,
    click,
    'key-press': keyPress,
    'toggle-on': toggleOn,
    'toggle-off': toggleOff,
    checkbox,
    select,
    deselect,
    hover,
    'tab-switch': tabSwitch,
    expand,
    collapse,
    'page-enter': pageEnter,
    'page-exit': pageExit,
    success,
    error,
    warning,
    notification,
    info,
    copy,
    send,
    delete: _delete,
    undo,
    pop,
    swoosh,
    slide,
  },
}
