// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
import type { StoryblokRichtext, StoryblokAsset, StoryblokMultiasset, StoryblokMultilink } from '../storyblok.d.ts';
export interface BlockBcorp {
  title?: string;
  headline?: StoryblokRichtext;
  copy?: StoryblokRichtext;
  cta_title?: string;
  cta?: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  theme?: number | string;
  overall_score?: string;
  qualify_score?: string;
  median_score?: string;
  max_score?: string;
  component: "block_bcorp";
  _uid: string;
}

export interface BlockContact {
  title?: string;
  headline?: StoryblokRichtext;
  info?: InfoItem[];
  theme?: number | string;
  component: "block_contact";
  _uid: string;
}

export interface BlockDivider {
  placement: "" | "inset" | "wide" | "full";
  spacing_top?: boolean;
  spacing_bottom?: boolean;
  theme?: "" | "dark" | "light";
  component: "block_divider";
  _uid: string;
}

export interface BlockEventOverview {
  copy: StoryblokRichtext;
  cta_title?: string;
  cta?: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  theme?: number | string;
  component: "block_event_overview";
  _uid: string;
}

export interface BlockEventText {
  title?: string;
  copy: StoryblokRichtext;
  cta_title?: string;
  cta?: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  theme?: number | string;
  component: "block_event_text";
  _uid: string;
}

export interface BlockFeaturedEvent {
  title?: string;
  headline?: StoryblokRichtext;
  event: ISbStoryData<Event> | string;
  cta_title?: string;
  cta?: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  theme?: number | string;
  component: "block_featured_event";
  _uid: string;
}

export interface BlockGallery {
  title?: string;
  items?: StoryblokMultiasset;
  theme?: number | string;
  component: "block_gallery";
  _uid: string;
}

export interface BlockHero {
  logo?: StoryblokAsset;
  max_width?: string;
  headline?: StoryblokRichtext;
  text?: StoryblokRichtext;
  media?: (Image | MuxVideoAutoplay)[];
  theme?: "" | "dark" | "light";
  component: "block_hero";
  _uid: string;
}

export interface BlockHeroBrand {
  headline?: StoryblokRichtext;
  headline_2?: StoryblokRichtext;
  text?: StoryblokRichtext;
  media?: (MuxVideoAutoplay | Image)[];
  logos?: StoryblokMultiasset;
  logo_strength?: unknown;
  logo_scale?: unknown;
  component: "block_hero_brand";
  _uid: string;
}

export interface BlockHoverGrid {
  title?: string;
  headline?: StoryblokRichtext;
  copy?: StoryblokRichtext;
  cta_title?: string;
  cta?: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  items?: ListItem[];
  theme?: number | string;
  accent?: number | string;
  component: "block_hover_grid";
  _uid: string;
}

export interface BlockHoverList {
  title?: string;
  headline?: StoryblokRichtext;
  copy?: StoryblokRichtext;
  cta_title?: string;
  cta?: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  items?: ListItem[];
  media?: (Image | MuxVideoAutoplay)[];
  theme?: number | string;
  accent?: number | string;
  component: "block_hover_list";
  _uid: string;
}

export interface BlockImpactDetails {
  title?: string;
  headline?: StoryblokRichtext;
  media?: Image[];
  copy?: StoryblokRichtext;
  cta_title?: string;
  cta?: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  logos?: StoryblokMultiasset;
  logo_strength?: unknown;
  logo_scale?: unknown;
  jaa_partnership?: boolean;
  theme?: number | string;
  component: "block_impact_details";
  _uid: string;
}

export interface BlockImpactStatement {
  items: TitleCopy[];
  theme?: number | string;
  component: "block_impact_statement";
  _uid: string;
}

export interface BlockLogoWall {
  title?: string;
  headline?: StoryblokRichtext;
  items: Logo[];
  theme?: number | string;
  component: "block_logo_wall";
  _uid: string;
}

export interface BlockMedia {
  title?: string;
  media?: (Image | MuxVideoAutoplay | MuxVideoPlayer)[];
  placement: "inset" | "wide" | "full";
  accent?: number | string;
  theme?: number | string;
  component: "block_media";
  _uid: string;
}

export interface BlockNextEvent {
  theme?: number | string;
  component: "block_next_event";
  _uid: string;
}

export interface BlockPastEvents {
  cta_title?: string;
  cta?: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  theme?: number | string;
  component: "block_past_events";
  _uid: string;
}

export interface BlockPosts {
  theme?: number | string;
  component: "block_posts";
  _uid: string;
}

export interface BlockProjectCarousel {
  title?: string;
  headline?: StoryblokRichtext;
  copy?: StoryblokRichtext;
  cta_title?: string;
  cta?: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  autoplay_delay?: string;
  projects: (ISbStoryData<Project> | string)[];
  theme?: number | string;
  component: "block_project_carousel";
  _uid: string;
}

export interface BlockProjectsFiltered {
  projects: (ISbStoryData<Project> | string)[];
  theme?: number | string;
  component: "block_projects_filtered";
  _uid: string;
}

export interface BlockProjectsSelected {
  title?: string;
  projects: (ISbStoryData<Project> | string)[];
  theme?: number | string;
  component: "block_projects_selected";
  _uid: string;
}

export interface BlockSplitText {
  items?: Copy[];
  theme?: number | string;
  component: "block_split_text";
  _uid: string;
}

export interface BlockTeam {
  teams: Team[];
  theme?: number | string;
  accent?: number | string;
  component: "block_team";
  _uid: string;
}

export interface BlockTestimonials {
  autoplay_delay?: string;
  items?: Testimonial[];
  media?: (Image | MuxVideoAutoplay)[];
  theme?: number | string;
  component: "block_testimonials";
  _uid: string;
}

export interface BlockText {
  copy?: StoryblokRichtext;
  component: "block_text";
  _uid: string;
}

export interface BlockTicker {
  media?: (Image | MuxVideoAutoplay)[];
  text?: string;
  logos: StoryblokMultiasset;
  logo_strength?: unknown;
  logo_scale?: unknown;
  theme?: number | string;
  component: "block_ticker";
  _uid: string;
}

export interface BlockTruths {
  title?: string;
  headline?: StoryblokRichtext;
  copy?: StoryblokRichtext;
  cta_title?: string;
  cta?: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  items?: ListItem[];
  bottom_headline?: string;
  bottom_copy?: string;
  theme?: number | string;
  component: "block_truths";
  _uid: string;
}

export interface BlockWorkText {
  title?: string;
  copy: StoryblokRichtext;
  autoplay_delay?: string;
  stats?: Copy[];
  logos?: StoryblokMultiasset;
  logo_strength?: unknown;
  logo_scale?: unknown;
  theme?: number | string;
  component: "block_work_text";
  _uid: string;
}

export interface Copy {
  copy?: StoryblokRichtext;
  component: "copy";
  _uid: string;
}

export interface Event {
  event_datetime: string;
  preview_image: StoryblokAsset;
  preview_text?: string;
  jaa_partnership?: boolean;
  blocks?: (
    | BlockBcorp
    | BlockDivider
    | BlockEventOverview
    | BlockEventText
    | BlockGallery
    | BlockHero
    | BlockHoverGrid
    | BlockHoverList
    | BlockImpactDetails
    | BlockImpactStatement
    | BlockLogoWall
    | BlockMedia
    | BlockPastEvents
    | BlockProjectCarousel
    | BlockSplitText
    | BlockTestimonials
    | BlockText
    | BlockTicker
  )[];
  seo_title: string;
  seo_description: string;
  seo_image: StoryblokAsset;
  component: "event";
  _uid: string;
}

export interface Image {
  image?: StoryblokAsset;
  component: "image";
  _uid: string;
}

export interface InfoItem {
  title?: string;
  column_one?: StoryblokRichtext;
  column_two?: StoryblokRichtext;
  media?: (Image | MuxVideoAutoplay | MuxVideoPlayer)[];
  component: "info_item";
  _uid: string;
}

export interface Link {
  title: string;
  link: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  component: "link";
  _uid: string;
}

export interface ListItem {
  title?: string;
  copy?: string;
  arrow_icon?: boolean;
  component: "list_item";
  _uid: string;
}

export interface Logo {
  image: StoryblokAsset;
  title?: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  component: "logo";
  _uid: string;
}

export interface MuxVideoAutoplay {
  poster?: StoryblokAsset;
  video: unknown;
  component: "mux_video_autoplay";
  _uid: string;
}

export interface MuxVideoPlayer {
  poster?: StoryblokAsset;
  video: unknown;
  name: string;
  data_capture?: boolean;
  component: "mux_video_player";
  _uid: string;
}

export interface Page {
  blocks?: (
    | BlockBcorp
    | BlockContact
    | BlockDivider
    | BlockFeaturedEvent
    | BlockGallery
    | BlockHero
    | BlockHeroBrand
    | BlockHoverGrid
    | BlockHoverList
    | BlockImpactDetails
    | BlockImpactStatement
    | BlockLogoWall
    | BlockMedia
    | BlockNextEvent
    | BlockPastEvents
    | BlockPosts
    | BlockProjectCarousel
    | BlockProjectsFiltered
    | BlockProjectsSelected
    | BlockSplitText
    | BlockTeam
    | BlockTestimonials
    | BlockText
    | BlockTicker
    | BlockTruths
  )[];
  seo_title: string;
  seo_description: string;
  seo_image: StoryblokAsset;
  component: "page";
  _uid: string;
}

export interface Person {
  image: StoryblokAsset;
  image_selected?: StoryblokAsset;
  name: string;
  biography?: string;
  position: string;
  email?: string;
  linkedin?: string;
  component: "person";
  _uid: string;
}

export interface Post {
  hero?: StoryblokAsset;
  author?: ISbStoryData<Person> | string;
  preview_image?: StoryblokAsset;
  preview_text?: string;
  category?: number | string;
  event_datetime?: string;
  seo_title?: string;
  seo_description?: string;
  seo_image?: StoryblokAsset;
  blocks?: (
    | PostGallery
    | PostHeading
    | PostHtml
    | PostImage
    | PostQuote
    | PostText
    | PostEmbed
    | PostWistia
    | MuxVideoPlayer
    | MuxVideoAutoplay
  )[];
  jaa_partnership?: boolean;
  component: "post";
  _uid: string;
}

export interface PostEmbed {
  url?: string;
  component: "post_embed";
  _uid: string;
}

export interface PostGallery {
  items?: StoryblokMultiasset;
  component: "post_gallery";
  _uid: string;
}

export interface PostHeading {
  heading?: string;
  component: "post_heading";
  _uid: string;
}

export interface PostHtml {
  html?: string;
  component: "post_html";
  _uid: string;
}

export interface PostImage {
  image?: StoryblokAsset;
  component: "post_image";
  _uid: string;
}

export interface PostQuote {
  quote?: StoryblokRichtext;
  citation?: string;
  component: "post_quote";
  _uid: string;
}

export interface PostText {
  text?: StoryblokRichtext;
  component: "post_text";
  _uid: string;
}

export interface PostWistia {
  id: string;
  component: "post_wistia";
  _uid: string;
}

export interface Project {
  preview_logo?: StoryblokAsset;
  preview_max_width?: string;
  preview_media: (Image | MuxVideoAutoplay)[];
  preview_headline: string;
  preview_text: string;
  category: number | string;
  blocks?: (
    | BlockDivider
    | BlockGallery
    | BlockHero
    | BlockImpactDetails
    | BlockImpactStatement
    | BlockMedia
    | BlockProjectsSelected
    | BlockTestimonials
    | BlockTicker
    | BlockTruths
    | BlockWorkText
  )[];
  seo_title: string;
  seo_description: string;
  seo_image: StoryblokAsset;
  component: "project";
  _uid: string;
}

export interface Settings {
  navigation?: Link[];
  statement?: StoryblokRichtext;
  statement_media?: (Image | MuxVideoAutoplay)[];
  cta_title?: string;
  cta_link?: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  newsletter_text?: string;
  newsletter_subtext?: StoryblokRichtext;
  links?: Link[];
  company_email?: string;
  company_telephone?: string;
  company_address?: string;
  logos?: Logo[];
  data_capture_headline: string;
  data_capture_text: StoryblokRichtext;
  component: "settings";
  _uid: string;
}

export interface Slide {
  project?: (ISbStoryData<Project> | string)[];
  logo?: StoryblokAsset;
  media?: (Image | MuxVideoAutoplay)[];
  copy?: StoryblokRichtext;
  component: "slide";
  _uid: string;
}

export interface Team {
  title?: string;
  people: (ISbStoryData<Person> | string)[];
  component: "team";
  _uid: string;
}

export interface Testimonial {
  quote?: string;
  name?: string;
  desc?: string;
  component: "testimonial";
  _uid: string;
}

export interface TitleCopy {
  title: StoryblokRichtext;
  copy: StoryblokRichtext;
  component: "title_copy";
  _uid: string;
}

export type ContentType = Event | Page | Person | Post | Project | Settings;
