// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
import type { StoryblokMultiasset, StoryblokMultilink, StoryblokAsset, StoryblokRichtext } from '../storyblok.d.ts';
export interface BlockCompanies {
  heading?: string;
  blocks?: ElementTicker[];
  theme?: number | string;
  id?: string;
  spacing_top?: boolean;
  spacing_bottom?: boolean;
  component: "block_companies";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockCta {
  text?: string;
  button?: ElementCta[];
  theme?: number | string;
  id?: string;
  spacing_top?: boolean;
  spacing_bottom?: boolean;
  component: "block_cta";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockHero {
  theme?: number | string;
  id?: string;
  component: "block_hero";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockHeroProject {
  image: StoryblokAsset;
  heading: string;
  copy?: StoryblokRichtext;
  theme?: number | string;
  id?: string;
  component: "block_hero_project";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockMedia {
  media: (ElementMediaImage | ElementMediaAutoplay)[];
  id?: string;
  theme?: number | string;
  spacing_top?: boolean;
  spacing_bottom?: boolean;
  component: "block_media";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockProjectOverview {
  heading: string;
  copy: StoryblokRichtext;
  theme?: number | string;
  id?: string;
  spacing_top?: boolean;
  spacing_bottom?: boolean;
  component: "block_project_overview";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockProjects {
  ticker?: string;
  projects?: (ISbStoryData<Project> | string)[];
  theme?: number | string;
  id?: string;
  spacing_top?: boolean;
  spacing_bottom?: boolean;
  component: "block_projects";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockServices {
  heading: string;
  copy: StoryblokRichtext;
  services?: (number | string)[];
  theme?: number | string;
  id?: string;
  spacing_top?: boolean;
  spacing_bottom?: boolean;
  component: "block_services";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockStatement {
  text: StoryblokRichtext;
  theme?: number | string;
  id?: string;
  spacing_top?: boolean;
  spacing_bottom?: boolean;
  component: "block_statement";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockSteps {
  heading: string;
  copy: StoryblokRichtext;
  theme?: number | string;
  steps?: ElementStep[];
  id?: string;
  spacing_top?: boolean;
  spacing_bottom?: boolean;
  component: "block_steps";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockTeam {
  heading: string;
  copy: StoryblokRichtext;
  cta?: ElementCta[];
  humans?: (ISbStoryData<Person> | string)[];
  theme?: number | string;
  id?: string;
  spacing_top?: boolean;
  spacing_bottom?: boolean;
  component: "block_team";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockTestimonial {
  quote: StoryblokRichtext;
  image?: StoryblokAsset;
  name?: string;
  position?: string;
  theme?: number | string;
  id?: string;
  spacing_top?: boolean;
  spacing_bottom?: boolean;
  component: "block_testimonial";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockText {
  text?: StoryblokRichtext;
  align_right?: boolean;
  theme?: number | string;
  id?: string;
  spacing_top?: boolean;
  spacing_bottom?: boolean;
  component: "block_text";
  _uid: string;
  _editable?: string | undefined;
}

export interface Client {
  name: string;
  component: "client";
  _uid: string;
  _editable?: string | undefined;
}

export interface ElementCta {
  text: string;
  link: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  theme?: number | string;
  component: "element_cta";
  _uid: string;
  _editable?: string | undefined;
}

export interface ElementLink {
  text: string;
  link: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  component: "element_link";
  _uid: string;
  _editable?: string | undefined;
}

export interface ElementMediaAutoplay {
  layout: "half" | "wide" | "full";
  poster?: StoryblokAsset;
  playback_id: string;
  component: "element_media_autoplay";
  _uid: string;
  _editable?: string | undefined;
}

export interface ElementMediaImage {
  layout: "half" | "wide" | "full";
  image: StoryblokAsset;
  component: "element_media_image";
  _uid: string;
  _editable?: string | undefined;
}

export interface ElementStep {
  title: string;
  heading?: string;
  copy?: StoryblokRichtext;
  image?: StoryblokAsset;
  theme?: number | string;
  component: "element_step";
  _uid: string;
  _editable?: string | undefined;
}

export interface ElementTicker {
  items?: StoryblokMultiasset;
  component: "element_ticker";
  _uid: string;
  _editable?: string | undefined;
}

export interface ElementTitle {
  title: string;
  component: "element_title";
  _uid: string;
  _editable?: string | undefined;
}

export interface Page {
  blocks?: (
    BlockCta | BlockProjects | BlockServices | BlockStatement | BlockSteps | BlockTeam | BlockHero | BlockCompanies
  )[];
  seo_title: string;
  seo_description: string;
  seo_image: StoryblokAsset;
  component: "page";
  _uid: string;
  _editable?: string | undefined;
}

export interface Person {
  image: StoryblokAsset;
  name: string;
  position?: string;
  component: "person";
  _uid: string;
  _editable?: string | undefined;
}

export interface Project {
  client: ISbStoryData<Client> | string;
  Credits?: ElementLink[];
  services?: (number | string)[];
  blocks?: (
    | BlockCta
    | BlockHeroProject
    | BlockMedia
    | BlockProjectOverview
    | BlockProjects
    | BlockStatement
    | BlockTestimonial
    | BlockText
  )[];
  title?: string;
  media?: StoryblokAsset;
  seo_title: string;
  seo_description: string;
  seo_image: StoryblokAsset;
  component: "project";
  _uid: string;
  _editable?: string | undefined;
}

export interface Seo {
  seo_title: string;
  seo_description: string;
  seo_image: StoryblokAsset;
  component: "seo";
  _uid: string;
  _editable?: string | undefined;
}

export interface Settings {
  tagline: string;
  navigation?: ElementLink[];
  footer_copy?: StoryblokRichtext;
  footer_copy_v2?: StoryblokRichtext;
  component: "settings";
  _uid: string;
  _editable?: string | undefined;
}

export type ContentType = Client | Page | Person | Project | Settings;
