// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokRichtext, StoryblokAsset } from '../storyblok.d.ts';
export interface BlockChips {
  heading?: string;
  copy?: StoryblokRichtext;
  theme?: number | string;
  component: "block_chips";
  _uid: string;
}

export interface BlockImage {
  media: StoryblokAsset;
  ratio: number | string;
  component: "block_image";
  _uid: string;
}

export interface BlockStatement {
  text?: StoryblokRichtext;
  theme?: number | string;
  component: "block_statement";
  _uid: string;
}

export interface BlockText {
  text?: StoryblokRichtext;
  component: "block_text";
  _uid: string;
}

export interface Page {
  blocks?: (BlockChips | BlockImage | BlockStatement | BlockText)[];
  seo_title: string;
  seo_description: string;
  seo_image: StoryblokAsset;
  component: "page";
  _uid: string;
}

export interface Project {
  blocks?: (BlockChips | BlockImage | BlockStatement | BlockText)[];
  seo_title: string;
  seo_description: string;
  seo_image: StoryblokAsset;
  component: "project";
  _uid: string;
}

export interface Seo {
  seo_title: string;
  seo_description: string;
  seo_image: StoryblokAsset;
  component: "seo";
  _uid: string;
}

export interface Settings {
  footer_copy?: StoryblokRichtext;
  footer_copy_v2?: StoryblokRichtext;
  component: "settings";
  _uid: string;
}

export type ContentType = Page | Project | Settings;
